# Generated by Django 4.1.6 on 2023-02-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_local',
        ),
    ]
